language:
  - c
  - node_js
node_js:
  - "0.10"
install:
  - npm install performance-now
before_script:
  - git fetch --unshallow
script:
  - ./tools/tarball-bootstrap -a && (make test ; make test.js)
  - (cd tests; cat test.log)
  - (cd js/tests ; cat test.log)
